//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL_EnglishCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<int> course_id { get; set; }
        public Nullable<int> student_id { get; set; }
    
        public virtual course course { get; set; }
        public virtual user user { get; set; }
    }
}
