//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL_EnglishCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam_details
    {
        public int id { get; set; }
        public Nullable<double> grade { get; set; }
        public string feedback { get; set; }
        public Nullable<int> exam_id { get; set; }
        public Nullable<int> student_id { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual user user { get; set; }
    }
}
