//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL_EnglishCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pbl3_english_centerEntities : DbContext
    {
        public pbl3_english_centerEntities()
            : base("name=pbl3_english_centerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<announcement> announcements { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<course_member> course_member { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<exam> exams { get; set; }
        public virtual DbSet<exam_details> exam_details { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<student_info> student_info { get; set; }
        public virtual DbSet<teacher_info> teacher_info { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
